# Generated by Django 3.2.4 on 2021-06-04 15:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='uid',
            field=models.CharField(default=uuid.uuid4, max_length=128),
        ),
        migrations.AddField(
            model_name='tag',
            name='uid',
            field=models.CharField(default=uuid.uuid4, max_length=128),
        ),
    ]
