# Generated by Django 3.2.4 on 2021-06-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210604_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meme',
            name='impression_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meme',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
